-- Seed the Briefings section with a curated set of top resources for small
-- business owners and operators. All are "link" briefings pointing to reputable,
-- stable landing pages. Additive; runs once on deploy.

INSERT INTO briefings (kind, title, summary, body, url, cover_key, author_id, published, published_at, status, submitted_by, created_at, updated_at) VALUES
  ('link', 'SBA Business Guide', 'The U.S. Small Business Administration''s step-by-step guide to planning, launching, managing, and growing a business.', '', 'https://www.sba.gov/business-guide', '', NULL, 1, (strftime('%s','now') * 1000) - 0,         'approved', NULL, (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'SCORE: Free Mentoring & Templates', 'Free business mentoring, templates, and workshops for small business owners, supported by the SBA.', '', 'https://www.score.org/', '', NULL, 1, (strftime('%s','now') * 1000) - 86400000,   'approved', NULL, (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'IRS Small Business Tax Center', 'Federal tax essentials for small business and self-employed: EINs, deductions, quarterly payments, and forms.', '', 'https://www.irs.gov/businesses/small-businesses-self-employed', '', NULL, 1, (strftime('%s','now') * 1000) - 172800000,  'approved', NULL, (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Y Combinator Startup Library', 'Essays and talks from YC on building product, fundraising, hiring, and growth.', '', 'https://www.ycombinator.com/library', '', NULL, 1, (strftime('%s','now') * 1000) - 259200000,  'approved', NULL, (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Paul Graham''s Essays', 'Foundational essays on startups, ideas, persistence, and doing great work.', '', 'https://www.paulgraham.com/articles.html', '', NULL, 1, (strftime('%s','now') * 1000) - 345600000,  'approved', NULL, (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'HBR on Entrepreneurship', 'Research-backed thinking from Harvard Business Review on starting and scaling a business.', '', 'https://hbr.org/topic/subject/entrepreneurship', '', NULL, 1, (strftime('%s','now') * 1000) - 432000000,  'approved', NULL, (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Shopify Business Blog', 'Practical guides on ecommerce, marketing, branding, and running a store.', '', 'https://www.shopify.com/blog', '', NULL, 1, (strftime('%s','now') * 1000) - 518400000,  'approved', NULL, (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'HubSpot Marketing Blog', 'Tactics for content, email, SEO, and inbound marketing from HubSpot.', '', 'https://blog.hubspot.com/marketing', '', NULL, 1, (strftime('%s','now') * 1000) - 604800000,  'approved', NULL, (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'First Round Review', 'In-depth operational advice from founders and operators who have built enduring companies.', '', 'https://review.firstround.com/', '', NULL, 1, (strftime('%s','now') * 1000) - 691200000,  'approved', NULL, (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Stripe Guides', 'Clear primers on incorporation, payments, taxes, and growing an online business.', '', 'https://stripe.com/guides', '', NULL, 1, (strftime('%s','now') * 1000) - 777600000,  'approved', NULL, (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Grow with Google: Small Business', 'Free training and tools from Google to build your online presence and reach customers.', '', 'https://grow.google/smallbusiness/', '', NULL, 1, (strftime('%s','now') * 1000) - 864000000,  'approved', NULL, (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Mailchimp Resources', 'Guides on email marketing, branding, automation, and customer growth.', '', 'https://mailchimp.com/resources/', '', NULL, 1, (strftime('%s','now') * 1000) - 950400000,  'approved', NULL, (strftime('%s','now') * 1000), (strftime('%s','now') * 1000));
