-- Friendlier DMA display names (e.g. "New York, NY - CT - NJ - PA" -> "New York City Metro").
-- Rewrites dma_name by stable dma_slug across the ZIP crosswalk and every table that
-- denormalizes it (members, companies, events, board topics). New signups inherit the
-- friendly name automatically since regionFromForm copies dma_name from zip_dma.
-- Additive migration; auto-applied by Webflow Cloud on deploy.

CREATE TABLE IF NOT EXISTS dma_pretty (slug TEXT PRIMARY KEY, name TEXT NOT NULL);
INSERT OR REPLACE INTO dma_pretty (slug, name) VALUES
  ('abilene-sweetwater-tx','Abilene Metro'),
  ('albany-ga','Albany, GA Metro'),
  ('albany-schenectady-troy-ny-ma-vt','Albany, NY Metro'),
  ('albuquerque-santa-fe-nm-az-co','Albuquerque–Santa Fe Metro'),
  ('alexandria-la','Alexandria Metro'),
  ('alpena-mi','Alpena Metro'),
  ('amarillo-tx-nm-ok','Amarillo Metro'),
  ('anchorage-ak','Anchorage Metro'),
  ('atlanta-ga-al-nc','Atlanta Metro'),
  ('augusta-ga-sc','Augusta Metro'),
  ('austin-tx','Austin Metro'),
  ('bakersfield-ca','Bakersfield Metro'),
  ('baltimore-md','Baltimore Metro'),
  ('bangor-me','Bangor Metro'),
  ('baton-rouge-la-ms','Baton Rouge Metro'),
  ('beaumont-port-arthur-tx','Beaumont Metro'),
  ('bend-or','Bend Metro'),
  ('billings-mt-id','Billings Metro'),
  ('biloxi-gulfport-ms','Biloxi Metro'),
  ('binghamton-ny','Binghamton Metro'),
  ('birmingham-al','Birmingham Metro'),
  ('bluefield-beckley-oak-hill-wv-va','Bluefield Metro'),
  ('boise-id-or','Boise Metro'),
  ('boston-ma-nh','Boston Metro'),
  ('bowling-green-ky','Bowling Green Metro'),
  ('buffalo-ny-pa','Buffalo Metro'),
  ('burlington-vt-plattsburgh-ny','Burlington Metro'),
  ('butte-bozeman-mt','Butte Metro'),
  ('casper-riverton-wy','Casper Metro'),
  ('cedar-rapids-waterloo-dubuque-ia-wi','Cedar Rapids Metro'),
  ('champaign-springfield-decatur-il','Champaign Metro'),
  ('charleston-huntington-wv-ky-oh','Charleston, WV Metro'),
  ('charleston-sc','Charleston, SC Metro'),
  ('charlotte-nc-sc','Charlotte Metro'),
  ('charlottesville-va','Charlottesville Metro'),
  ('chattanooga-tn-ga-nc','Chattanooga Metro'),
  ('cheyenne-scottsbluff-sterling-wy-ne','Cheyenne Metro'),
  ('chicago-il-in','Chicago Metro'),
  ('chico-redding-ca','Chico Metro'),
  ('cincinnati-oh-in-ky','Cincinnati Metro'),
  ('clarksburg-weston-wv','Clarksburg Metro'),
  ('cleveland-oh','Cleveland Metro'),
  ('colorado-springs-pueblo-co','Colorado Springs Metro'),
  ('columbia-jefferson-city-mo','Columbia, MO Metro'),
  ('columbia-sc','Columbia, SC Metro'),
  ('columbus-ga-al','Columbus, GA Metro'),
  ('columbus-oh','Columbus, OH Metro'),
  ('columbus-tupelo-west-point-ms-al','Columbus, MS Metro'),
  ('corpus-christi-tx','Corpus Christi Metro'),
  ('dallas-ft-worth-tx','Dallas–Fort Worth Metro'),
  ('davenport-rock-island-moline-ia-il','Davenport Metro'),
  ('dayton-oh-in','Dayton Metro'),
  ('denver-co-ne-nv-wy','Denver Metro'),
  ('des-moines-ames-ia-mo','Des Moines Metro'),
  ('detroit-mi','Detroit Metro'),
  ('dothan-al-ga','Dothan Metro'),
  ('duluth-superior-mn-mi-wi','Duluth Metro'),
  ('el-paso-tx-nm','El Paso Metro'),
  ('elmira-ny-pa','Elmira Metro'),
  ('erie-pa','Erie Metro'),
  ('eugene-or','Eugene Metro'),
  ('eureka-ca','Eureka Metro'),
  ('evansville-in-il-ky','Evansville Metro'),
  ('fairbanks-ak','Fairbanks Metro'),
  ('fargo-valley-city-nd-mn','Fargo Metro'),
  ('flint-saginaw-bay-city-mi','Flint Metro'),
  ('florence-myrtle-beach-sc-nc','Florence Metro'),
  ('fresno-visalia-ca','Fresno Metro'),
  ('ft-myers-naples-fl','Fort Myers–Naples Metro'),
  ('ft-smith-fay-springdale-rogers-ar-ok','Fort Smith Metro'),
  ('ft-wayne-in-oh','Fort Wayne Metro'),
  ('gainesville-fl','Gainesville Metro'),
  ('glendive-mt','Glendive Metro'),
  ('grand-junction-montrose-co','Grand Junction Metro'),
  ('grand-rapids-kalamazoo-battle-creek-mi','Grand Rapids Metro'),
  ('great-falls-mt','Great Falls Metro'),
  ('green-bay-appleton-wi-mi','Green Bay Metro'),
  ('greensboro-h-point-w-salem-nc-va','Greensboro Metro'),
  ('greenville-new-bern-washington-nc','Greenville, NC Metro'),
  ('greenville-spartanburg-sc-asheville-and-nc-ga','Greenville–Spartanburg Metro'),
  ('greenwood-greenville-ms','Greenwood Metro'),
  ('harlingen-weslaco-brownsville-mcallen-tx','Rio Grande Valley'),
  ('harrisburg-lancaster-lebanon-york-pa','Harrisburg Metro'),
  ('harrisonburg-va-wv','Harrisonburg Metro'),
  ('hartford-new-haven-ct','Hartford–New Haven Metro'),
  ('hattiesburg-laurel-ms','Hattiesburg Metro'),
  ('helena-mt','Helena Metro'),
  ('honolulu-hi','Honolulu Metro'),
  ('houston-tx','Houston Metro'),
  ('huntsville-decatur-florence-al-tn','Huntsville Metro'),
  ('idaho-falls-pocatello-id-wy','Idaho Falls Metro'),
  ('indianapolis-in','Indianapolis Metro'),
  ('jackson-ms','Jackson, MS Metro'),
  ('jackson-tn','Jackson, TN Metro'),
  ('jacksonville-fl-brunswick-ga','Jacksonville Metro'),
  ('johnstown-altoona-pa','Johnstown Metro'),
  ('jonesboro-ar-mo','Jonesboro Metro'),
  ('joplin-pittsburg-mo-ks-ok','Joplin Metro'),
  ('juneau-ak','Juneau Metro'),
  ('kansas-city-mo-ks','Kansas City Metro'),
  ('knoxville-tn-ky','Knoxville Metro'),
  ('lacrosse-eau-claire-wi-mn','La Crosse Metro'),
  ('lafayette-in','Lafayette, IN Metro'),
  ('lafayette-la','Lafayette, LA Metro'),
  ('lake-charles-la','Lake Charles Metro'),
  ('lansing-mi','Lansing Metro'),
  ('laredo-tx','Laredo Metro'),
  ('las-vegas-nv','Las Vegas Metro'),
  ('lexington-ky','Lexington Metro'),
  ('lima-oh','Lima Metro'),
  ('lincoln-hastings-kearney-plus-ne-ks','Lincoln Metro'),
  ('little-rock-pine-bluff-ar','Little Rock Metro'),
  ('los-angeles-ca','Los Angeles Metro'),
  ('louisville-ky-in','Louisville Metro'),
  ('lubbock-tx','Lubbock Metro'),
  ('macon-ga','Macon Metro'),
  ('madison-wi','Madison Metro'),
  ('mankato-mn-ia','Mankato Metro'),
  ('marquette-mi','Marquette Metro'),
  ('medford-klamath-falls-or-ca','Medford Metro'),
  ('memphis-tn-ar-ms-mo','Memphis Metro'),
  ('meridian-ms-al','Meridian Metro'),
  ('miami-ft-lauderdale-fl','Miami Metro'),
  ('milwaukee-wi','Milwaukee Metro'),
  ('minneapolis-st-paul-mn-wi','Minneapolis–St. Paul Metro'),
  ('minot-bismarck-dickinson-nd-mt-sd','Minot Metro'),
  ('missoula-mt','Missoula Metro'),
  ('mobile-al-pensacola-fl-ms','Mobile–Pensacola Metro'),
  ('monroe-el-dorado-la-ar','Monroe Metro'),
  ('monterey-salinas-ca','Monterey Metro'),
  ('montgomery-al','Montgomery Metro'),
  ('nashville-tn-ky','Nashville Metro'),
  ('new-orleans-la-ms','New Orleans Metro'),
  ('new-york-ny-ct-nj-pa','New York City Metro'),
  ('norfolk-portsmouth-newport-news-va-nc','Hampton Roads'),
  ('north-platte-ne','North Platte Metro'),
  ('odessa-midland-tx','Odessa Metro'),
  ('oklahoma-city-ok','Oklahoma City Metro'),
  ('omaha-ne-ia-mo','Omaha Metro'),
  ('orlando-daytona-beach-melbourne-fl','Orlando Metro'),
  ('ottumwa-kirksville-ia-mo','Ottumwa Metro'),
  ('paducah-cape-giradeau-harrisburg-ky-il-mo-tn','Paducah Metro'),
  ('palm-springs-ca','Palm Springs Metro'),
  ('panama-city-fl','Panama City Metro'),
  ('parkersburg-wv-oh','Parkersburg Metro'),
  ('peoria-bloomington-il','Peoria Metro'),
  ('philadelphia-pa-de-nj','Philadelphia Metro'),
  ('phoenix-az','Phoenix Metro'),
  ('pittsburgh-pa-md-wv','Pittsburgh Metro'),
  ('portland-auburn-me-nh-vt','Portland, ME Metro'),
  ('portland-or-wa','Portland, OR Metro'),
  ('presque-isle-me','Presque Isle Metro'),
  ('providence-ri-new-bedford-ma','Providence Metro'),
  ('quincy-hannibal-keokuk-mo-il-ia','Quincy Metro'),
  ('raleigh-durham-nc-va','Raleigh–Durham Metro'),
  ('rapid-city-sd-mt-ne-wy','Rapid City Metro'),
  ('reno-nv-ca','Reno Metro'),
  ('richmond-petersburg-va','Richmond Metro'),
  ('roanoke-lynchburg-va-wv','Roanoke Metro'),
  ('rochester-mason-city-austin-mn-ia','Rochester, MN Metro'),
  ('rochester-ny','Rochester, NY Metro'),
  ('rockford-il','Rockford Metro'),
  ('sacramento-stockton-modesto-ca','Sacramento Metro'),
  ('salisbury-md-de','Salisbury Metro'),
  ('salt-lake-city-ut-id-wy','Salt Lake City Metro'),
  ('san-angelo-tx','San Angelo Metro'),
  ('san-antonio-tx','San Antonio Metro'),
  ('san-diego-ca','San Diego Metro'),
  ('san-francisco-oakland-san-jose-ca','San Francisco Bay Area'),
  ('santa-barbara-santa-maria-san-luis-obispo-ca','Santa Barbara Metro'),
  ('savannah-ga-sc','Savannah Metro'),
  ('seattle-tacoma-wa','Seattle Metro'),
  ('sherman-ada-ok-tx','Sherman Metro'),
  ('shreveport-la-ar-ok-tx','Shreveport Metro'),
  ('sioux-city-ia-ne-sd','Sioux City Metro'),
  ('sioux-falls-mitchell-sd-ia-mn-ne','Sioux Falls Metro'),
  ('south-bend-elkhart-in-mi','South Bend Metro'),
  ('spokane-wa-id-mt-or','Spokane Metro'),
  ('springfield-holyoke-ma','Springfield, MA Metro'),
  ('springfield-mo-ar','Springfield, MO Metro'),
  ('st-joseph-mo-ks','St. Joseph Metro'),
  ('st-louis-mo-il','St. Louis Metro'),
  ('syracuse-ny-dma','Syracuse Metro'),
  ('tallahassee-thomasville-fl-ga','Tallahassee Metro'),
  ('tampa-st-petersburg-sarasota-fl','Tampa Bay Metro'),
  ('terre-haute-in-il','Terre Haute Metro'),
  ('toledo-oh-mi','Toledo Metro'),
  ('topeka-ks','Topeka Metro'),
  ('traverse-city-cadillac-mi','Traverse City Metro'),
  ('tri-cities-tn-va-ky','Tri-Cities Metro'),
  ('tucson-nogales-az','Tucson Metro'),
  ('tulsa-ok-ks','Tulsa Metro'),
  ('twin-falls-id','Twin Falls Metro'),
  ('tyler-longview-lufkin-nacogdoches-tx','Tyler Metro'),
  ('unmeasured-ak','Other (Alaska)'),
  ('utica-ny-dma','Utica Metro'),
  ('victoria-tx','Victoria Metro'),
  ('waco-temple-bryan-tx','Waco Metro'),
  ('washington-dc-md-pa-va-wv','Washington, D.C. Metro'),
  ('watertown-ny','Watertown Metro'),
  ('wausau-rhinelander-wi','Wausau Metro'),
  ('west-palm-beach-ft-pierce-fl','West Palm Beach Metro'),
  ('wheeling-steubenville-wv-oh','Wheeling Metro'),
  ('wichita-falls-lawton-tx-ok','Wichita Falls Metro'),
  ('wichita-hutchinson-plus-ks-ne','Wichita Metro'),
  ('wilkes-barre-scranton-pa','Scranton–Wilkes-Barre Metro'),
  ('wilmington-nc','Wilmington Metro'),
  ('yakima-pasco-richland-kennewick-wa-or','Yakima Metro'),
  ('youngstown-oh-pa','Youngstown Metro'),
  ('yuma-el-centro-az-ca','Yuma Metro'),
  ('zanesville-oh','Zanesville Metro');

UPDATE zip_dma SET dma_name = (SELECT name FROM dma_pretty WHERE slug = zip_dma.dma_slug) WHERE dma_slug IN (SELECT slug FROM dma_pretty);
UPDATE users SET dma_name = (SELECT name FROM dma_pretty WHERE slug = users.dma_slug) WHERE dma_slug IN (SELECT slug FROM dma_pretty);
UPDATE companies SET dma_name = (SELECT name FROM dma_pretty WHERE slug = companies.dma_slug) WHERE dma_slug IN (SELECT slug FROM dma_pretty);
UPDATE events SET dma_name = (SELECT name FROM dma_pretty WHERE slug = events.dma_slug) WHERE dma_slug IN (SELECT slug FROM dma_pretty);
UPDATE topics SET dma_name = (SELECT name FROM dma_pretty WHERE slug = topics.dma_slug) WHERE dma_slug IN (SELECT slug FROM dma_pretty);

DROP TABLE dma_pretty;
