-- Fill out the Briefings section to ~12 per topic with curated, stable
-- external resources for owners and operators (same 'link' pattern as 0014).
-- Tops up each briefing_category, accounting for the briefings 0014/0016
-- already filed. Additive; runs once on deploy.

-- marketing (+8)
INSERT INTO briefings (kind, title, summary, body, url, cover_key, author_id, published, published_at, status, submitted_by, category_id, created_at, updated_at) VALUES
  ('link', 'Think with Google', 'Consumer insights, trends, and measurement thinking from Google''s research teams.', '', 'https://www.thinkwithgoogle.com/', '', NULL, 1, (strftime('%s','now') * 1000) - 3600000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'marketing'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Content Marketing Institute', 'Research, frameworks, and how-tos for building a content strategy that compounds.', '', 'https://contentmarketinginstitute.com/', '', NULL, 1, (strftime('%s','now') * 1000) - 7200000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'marketing'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Moz Blog', 'SEO fundamentals, technical guides, and search trends from the Moz team.', '', 'https://moz.com/blog', '', NULL, 1, (strftime('%s','now') * 1000) - 10800000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'marketing'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Ahrefs Blog', 'Practical, data-backed tactics for SEO and content that ranks.', '', 'https://ahrefs.com/blog/', '', NULL, 1, (strftime('%s','now') * 1000) - 14400000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'marketing'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Sprout Social Insights', 'Social strategy, benchmarks, and brand-building research.', '', 'https://sproutsocial.com/insights/', '', NULL, 1, (strftime('%s','now') * 1000) - 18000000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'marketing'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Nielsen Insights', 'Audience measurement and media-consumption research across channels.', '', 'https://www.nielsen.com/insights/', '', NULL, 1, (strftime('%s','now') * 1000) - 21600000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'marketing'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Ad Age', 'News and analysis on advertising, brands, agencies, and media.', '', 'https://adage.com/', '', NULL, 1, (strftime('%s','now') * 1000) - 25200000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'marketing'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Marketing Week', 'Commentary, careers, and case studies for marketing leaders.', '', 'https://www.marketingweek.com/', '', NULL, 1, (strftime('%s','now') * 1000) - 28800000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'marketing'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000));

-- finance-tax (+10)
INSERT INTO briefings (kind, title, summary, body, url, cover_key, author_id, published, published_at, status, submitted_by, category_id, created_at, updated_at) VALUES
  ('link', 'QuickBooks Resource Center', 'Bookkeeping, cash flow, and accounting guides for small business.', '', 'https://quickbooks.intuit.com/r/', '', NULL, 1, (strftime('%s','now') * 1000) - 32400000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'finance-tax'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Xero Small Business Guides', 'Plain-English guides to accounting and running the numbers.', '', 'https://www.xero.com/us/guides/', '', NULL, 1, (strftime('%s','now') * 1000) - 36000000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'finance-tax'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Investopedia: Small Business', 'Definitions and explainers across finance, accounting, and tax.', '', 'https://www.investopedia.com/small-business-4427743', '', NULL, 1, (strftime('%s','now') * 1000) - 39600000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'finance-tax'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'NerdWallet: Small Business', 'Comparisons and guidance on financing, cards, and taxes.', '', 'https://www.nerdwallet.com/small-business', '', NULL, 1, (strftime('%s','now') * 1000) - 43200000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'finance-tax'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Tax Foundation', 'Independent analysis of federal and state tax policy.', '', 'https://taxfoundation.org/', '', NULL, 1, (strftime('%s','now') * 1000) - 46800000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'finance-tax'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'AICPA & CIMA', 'Standards, research, and resources from the accounting profession.', '', 'https://www.aicpa-cima.com/', '', NULL, 1, (strftime('%s','now') * 1000) - 50400000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'finance-tax'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Gusto Resources', 'Payroll, benefits, and people-finance how-tos for employers.', '', 'https://gusto.com/resources', '', NULL, 1, (strftime('%s','now') * 1000) - 54000000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'finance-tax'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Ramp Blog', 'Spend management, controls, and finance-operations playbooks.', '', 'https://ramp.com/blog', '', NULL, 1, (strftime('%s','now') * 1000) - 57600000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'finance-tax'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Brex Journal', 'Finance and cash strategy for growing companies.', '', 'https://www.brex.com/journal', '', NULL, 1, (strftime('%s','now') * 1000) - 61200000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'finance-tax'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Corporate Finance Institute', 'Free fundamentals on accounting, modeling, and corporate finance.', '', 'https://corporatefinanceinstitute.com/', '', NULL, 1, (strftime('%s','now') * 1000) - 64800000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'finance-tax'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000));

-- operations (+11)
INSERT INTO briefings (kind, title, summary, body, url, cover_key, author_id, published, published_at, status, submitted_by, category_id, created_at, updated_at) VALUES
  ('link', 'Asana Resources', 'Guides and templates for project and work management.', '', 'https://asana.com/resources', '', NULL, 1, (strftime('%s','now') * 1000) - 68400000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'operations'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Atlassian Blog', 'Teamwork, agile practices, and operating cadence from Atlassian.', '', 'https://www.atlassian.com/blog', '', NULL, 1, (strftime('%s','now') * 1000) - 72000000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'operations'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Notion Help & Guides', 'Set up docs, wikis, and systems that keep a team aligned.', '', 'https://www.notion.so/help', '', NULL, 1, (strftime('%s','now') * 1000) - 75600000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'operations'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Zapier Blog', 'Automation and workflow efficiency for lean teams.', '', 'https://zapier.com/blog/', '', NULL, 1, (strftime('%s','now') * 1000) - 79200000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'operations'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'McKinsey on Operations', 'Operations research and benchmarks for operators.', '', 'https://www.mckinsey.com/capabilities/operations/our-insights', '', NULL, 1, (strftime('%s','now') * 1000) - 82800000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'operations'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'MIT Sloan Management Review', 'Management and operations research for practitioners.', '', 'https://sloanreview.mit.edu/', '', NULL, 1, (strftime('%s','now') * 1000) - 86400000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'operations'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Lean Enterprise Institute', 'Lean thinking and continuous-improvement methods.', '', 'https://www.lean.org/', '', NULL, 1, (strftime('%s','now') * 1000) - 90000000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'operations'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'ASCM (Supply Chain)', 'Standards and education for supply chain and operations.', '', 'https://www.ascm.org/', '', NULL, 1, (strftime('%s','now') * 1000) - 93600000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'operations'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Process Street Blog', 'Building SOPs and repeatable processes that scale.', '', 'https://www.process.st/blog/', '', NULL, 1, (strftime('%s','now') * 1000) - 97200000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'operations'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'SHRM', 'People operations, compliance, and HR best practices.', '', 'https://www.shrm.org/', '', NULL, 1, (strftime('%s','now') * 1000) - 100800000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'operations'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Trello Guides', 'Lightweight systems for organizing work and teams.', '', 'https://trello.com/guide', '', NULL, 1, (strftime('%s','now') * 1000) - 104400000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'operations'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000));

-- sales (+12)
INSERT INTO briefings (kind, title, summary, body, url, cover_key, author_id, published, published_at, status, submitted_by, category_id, created_at, updated_at) VALUES
  ('link', 'HubSpot Sales Blog', 'Prospecting, pipeline, and closing tactics for sales teams.', '', 'https://blog.hubspot.com/sales', '', NULL, 1, (strftime('%s','now') * 1000) - 108000000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'sales'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Salesforce Blog', 'Selling, CRM, and revenue-operations guidance.', '', 'https://www.salesforce.com/blog/', '', NULL, 1, (strftime('%s','now') * 1000) - 111600000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'sales'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Gong Labs', 'Data-driven insights on what actually works in sales conversations.', '', 'https://www.gong.io/blog/', '', NULL, 1, (strftime('%s','now') * 1000) - 115200000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'sales'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Pavilion', 'Community and resources for go-to-market leaders.', '', 'https://www.joinpavilion.com/', '', NULL, 1, (strftime('%s','now') * 1000) - 118800000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'sales'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Close Blog', 'Inside-sales process, follow-up, and outreach that converts.', '', 'https://blog.close.com/', '', NULL, 1, (strftime('%s','now') * 1000) - 122400000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'sales'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Pipedrive Blog', 'CRM discipline and pipeline management for small teams.', '', 'https://www.pipedrive.com/en/blog', '', NULL, 1, (strftime('%s','now') * 1000) - 126000000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'sales'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Sandler Resources', 'A durable sales methodology and training library.', '', 'https://www.sandler.com/resources/', '', NULL, 1, (strftime('%s','now') * 1000) - 129600000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'sales'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'RAIN Group Blog', 'Research-backed selling skills and methodology.', '', 'https://www.rainsalestraining.com/blog', '', NULL, 1, (strftime('%s','now') * 1000) - 133200000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'sales'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'LinkedIn Sales Blog', 'Social selling and prospecting on the platform buyers use.', '', 'https://www.linkedin.com/business/sales/blog', '', NULL, 1, (strftime('%s','now') * 1000) - 136800000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'sales'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Outreach Resources', 'Sales engagement and sequencing best practices.', '', 'https://www.outreach.io/resources', '', NULL, 1, (strftime('%s','now') * 1000) - 140400000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'sales'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Highspot Blog', 'Sales enablement, content, and rep readiness.', '', 'https://www.highspot.com/blog/', '', NULL, 1, (strftime('%s','now') * 1000) - 144000000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'sales'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'HBR: Sales', 'Research on selling, sales management, and incentives.', '', 'https://hbr.org/topic/subject/sales', '', NULL, 1, (strftime('%s','now') * 1000) - 147600000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'sales'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000));

-- legal (+12)
INSERT INTO briefings (kind, title, summary, body, url, cover_key, author_id, published, published_at, status, submitted_by, category_id, created_at, updated_at) VALUES
  ('link', 'Nolo', 'Plain-English legal guides for small business and contracts.', '', 'https://www.nolo.com/', '', NULL, 1, (strftime('%s','now') * 1000) - 151200000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'legal'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'SBA: Choose a Business Structure', 'Compare LLC, S-corp, and other structures before you file.', '', 'https://www.sba.gov/business-guide/launch-your-business/choose-business-structure', '', NULL, 1, (strftime('%s','now') * 1000) - 154800000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'legal'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'LegalZoom Articles', 'Formation, contracts, and compliance basics explained.', '', 'https://www.legalzoom.com/articles', '', NULL, 1, (strftime('%s','now') * 1000) - 158400000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'legal'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Cooley GO', 'Free startup legal resources and document generators.', '', 'https://www.cooleygo.com/', '', NULL, 1, (strftime('%s','now') * 1000) - 162000000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'legal'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Stripe Atlas Guides', 'Incorporation, equity, and early legal/ops guides.', '', 'https://stripe.com/atlas/guides', '', NULL, 1, (strftime('%s','now') * 1000) - 165600000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'legal'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Y Combinator: Standard Documents', 'The SAFE and other standardized financing documents.', '', 'https://www.ycombinator.com/documents', '', NULL, 1, (strftime('%s','now') * 1000) - 169200000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'legal'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'USPTO: Trademark Basics', 'Protect your brand name and marks the right way.', '', 'https://www.uspto.gov/trademarks/basics', '', NULL, 1, (strftime('%s','now') * 1000) - 172800000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'legal'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'U.S. Copyright Office', 'Copyright basics for original work and content.', '', 'https://www.copyright.gov/', '', NULL, 1, (strftime('%s','now') * 1000) - 176400000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'legal'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'FTC Business Guidance', 'Advertising, privacy, and consumer-protection rules.', '', 'https://www.ftc.gov/business-guidance', '', NULL, 1, (strftime('%s','now') * 1000) - 180000000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'legal'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'DOL: Workplace Topics', 'Federal employment and labor-law topics for employers.', '', 'https://www.dol.gov/general/topics', '', NULL, 1, (strftime('%s','now') * 1000) - 183600000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'legal'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Justia', 'Free legal information, codes, and case law.', '', 'https://www.justia.com/', '', NULL, 1, (strftime('%s','now') * 1000) - 187200000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'legal'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Clerky', 'Startup legal paperwork done correctly the first time.', '', 'https://www.clerky.com/', '', NULL, 1, (strftime('%s','now') * 1000) - 190800000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'legal'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000));

-- technology (+12)
INSERT INTO briefings (kind, title, summary, body, url, cover_key, author_id, published, published_at, status, submitted_by, category_id, created_at, updated_at) VALUES
  ('link', 'Stack Overflow', 'The reference Q&A for developers and technical teams.', '', 'https://stackoverflow.com/', '', NULL, 1, (strftime('%s','now') * 1000) - 194400000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'technology'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'GitHub Resources', 'Engineering, DevOps, and developer-experience guides.', '', 'https://resources.github.com/', '', NULL, 1, (strftime('%s','now') * 1000) - 198000000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'technology'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'AWS Architecture Center', 'Reference architectures and well-architected guidance.', '', 'https://aws.amazon.com/architecture/', '', NULL, 1, (strftime('%s','now') * 1000) - 201600000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'technology'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Google Cloud Architecture Center', 'Patterns and best practices for building on the cloud.', '', 'https://cloud.google.com/architecture', '', NULL, 1, (strftime('%s','now') * 1000) - 205200000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'technology'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Andreessen Horowitz (a16z)', 'Analysis of software, AI, and technology trends.', '', 'https://a16z.com/', '', NULL, 1, (strftime('%s','now') * 1000) - 208800000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'technology'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Stratechery', 'Strategic analysis of technology and media business models.', '', 'https://stratechery.com/', '', NULL, 1, (strftime('%s','now') * 1000) - 212400000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'technology'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'MIT Technology Review', 'Independent reporting on emerging technology.', '', 'https://www.technologyreview.com/', '', NULL, 1, (strftime('%s','now') * 1000) - 216000000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'technology'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'The Pragmatic Engineer', 'Engineering practice and leadership for software teams.', '', 'https://newsletter.pragmaticengineer.com/', '', NULL, 1, (strftime('%s','now') * 1000) - 219600000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'technology'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'OWASP', 'Application-security fundamentals and the Top Ten.', '', 'https://owasp.org/', '', NULL, 1, (strftime('%s','now') * 1000) - 223200000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'technology'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'NIST Cybersecurity', 'The Cybersecurity Framework and practical guidance.', '', 'https://www.nist.gov/cybersecurity', '', NULL, 1, (strftime('%s','now') * 1000) - 226800000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'technology'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'CISA Resources & Tools', 'Security guidance for businesses from CISA.', '', 'https://www.cisa.gov/resources-tools/resources', '', NULL, 1, (strftime('%s','now') * 1000) - 230400000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'technology'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Wired: Business', 'Reporting on technology''s impact on business.', '', 'https://www.wired.com/category/business/', '', NULL, 1, (strftime('%s','now') * 1000) - 234000000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'technology'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000));

-- leadership (+8)
INSERT INTO briefings (kind, title, summary, body, url, cover_key, author_id, published, published_at, status, submitted_by, category_id, created_at, updated_at) VALUES
  ('link', 'HBR: Leadership', 'Research and practice on leading teams and organizations.', '', 'https://hbr.org/topic/subject/leadership', '', NULL, 1, (strftime('%s','now') * 1000) - 237600000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'leadership'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'McKinsey on Leadership', 'Featured insights on leadership and organizational health.', '', 'https://www.mckinsey.com/featured-insights/leadership', '', NULL, 1, (strftime('%s','now') * 1000) - 241200000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'leadership'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Farnam Street', 'Mental models and clearer decision-making.', '', 'https://fs.blog/', '', NULL, 1, (strftime('%s','now') * 1000) - 244800000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'leadership'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Lenny''s Newsletter', 'Product, growth, and leadership for builders and operators.', '', 'https://www.lennysnewsletter.com/', '', NULL, 1, (strftime('%s','now') * 1000) - 248400000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'leadership'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Stanford GSB Insights', 'Management research translated for practitioners.', '', 'https://www.gsb.stanford.edu/insights', '', NULL, 1, (strftime('%s','now') * 1000) - 252000000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'leadership'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Knowledge at Wharton', 'Business research and analysis from Wharton faculty.', '', 'https://knowledge.wharton.upenn.edu/', '', NULL, 1, (strftime('%s','now') * 1000) - 255600000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'leadership'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Korn Ferry Insights', 'Leadership, talent, and organizational development.', '', 'https://www.kornferry.com/insights', '', NULL, 1, (strftime('%s','now') * 1000) - 259200000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'leadership'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Reforge Blog', 'Frameworks for growth, product, and leadership at scale.', '', 'https://www.reforge.com/blog', '', NULL, 1, (strftime('%s','now') * 1000) - 262800000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'leadership'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000));

-- funding (+11)
INSERT INTO briefings (kind, title, summary, body, url, cover_key, author_id, published, published_at, status, submitted_by, category_id, created_at, updated_at) VALUES
  ('link', 'SBA: Funding Programs', 'Loans, grants, and federal funding options for small business.', '', 'https://www.sba.gov/funding-programs', '', NULL, 1, (strftime('%s','now') * 1000) - 266400000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'funding'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'NVCA', 'Resources and data from the National Venture Capital Association.', '', 'https://nvca.org/', '', NULL, 1, (strftime('%s','now') * 1000) - 270000000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'funding'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Crunchbase News', 'Funding news, rounds, and private-market trends.', '', 'https://news.crunchbase.com/', '', NULL, 1, (strftime('%s','now') * 1000) - 273600000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'funding'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'PitchBook News', 'Private-market and venture data, analysis, and reports.', '', 'https://pitchbook.com/news', '', NULL, 1, (strftime('%s','now') * 1000) - 277200000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'funding'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Carta: Learn', 'Cap tables, equity, and fundraising mechanics explained.', '', 'https://carta.com/learn/', '', NULL, 1, (strftime('%s','now') * 1000) - 280800000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'funding'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Techstars', 'Accelerator playbooks and resources for founders.', '', 'https://www.techstars.com/', '', NULL, 1, (strftime('%s','now') * 1000) - 284400000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'funding'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Kauffman Foundation', 'Research and tools on entrepreneurship and capital access.', '', 'https://www.kauffman.org/', '', NULL, 1, (strftime('%s','now') * 1000) - 288000000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'funding'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'SaaStr', 'Scaling and fundraising lessons for software founders.', '', 'https://www.saastr.com/', '', NULL, 1, (strftime('%s','now') * 1000) - 291600000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'funding'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'NFX', 'Frameworks and guides for founders raising capital.', '', 'https://www.nfx.com/', '', NULL, 1, (strftime('%s','now') * 1000) - 295200000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'funding'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'Visible.vc Blog', 'Investor updates, metrics, and fundraising guidance.', '', 'https://visible.vc/blog/', '', NULL, 1, (strftime('%s','now') * 1000) - 298800000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'funding'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)),
  ('link', 'AngelList', 'Tools and resources for startups and early-stage investors.', '', 'https://www.angellist.com/', '', NULL, 1, (strftime('%s','now') * 1000) - 302400000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'funding'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000));

