-- Import the latest pitchblende.net Insights posts (published after the 0034
-- backfill) as 'link' briefings, filed under the closest portal topic
-- (Performance Marketing + Brand & Growth -> Marketing). Each links to
-- https://www.pitchblende.net/insights/<slug> and carries the post's cover
-- image, pulled from the pitchblende Webflow CMS. Additive; runs once on
-- deploy. The NOT EXISTS guard makes each row idempotent by URL so a post is
-- never briefed twice.

INSERT INTO briefings (kind, title, summary, body, url, cover_key, cover_url, author_id, published, published_at, status, submitted_by, category_id, created_at, updated_at)
SELECT 'link', 'We''ve Sat on Both Sides of the Table. That''s the Difference.', 'Big-agency craft is common. So is in-house ownership. Having both in the same room is rare, and it changes what a marketing partner can promise you.', '', 'https://www.pitchblende.net/insights/weve-sat-on-both-sides-of-the-table', '', 'https://cdn.prod.website-files.com/6a162fda8d635e31a20caa65/6a301e772c10b65f942e23af_6a301e08b635cc5cf8933092_cover_brand_v2_split_logo_2400x1350.png', NULL, 1, 1781481600000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'marketing'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)
WHERE NOT EXISTS (SELECT 1 FROM briefings WHERE url = 'https://www.pitchblende.net/insights/weve-sat-on-both-sides-of-the-table');

INSERT INTO briefings (kind, title, summary, body, url, cover_key, cover_url, author_id, published, published_at, status, submitted_by, category_id, created_at, updated_at)
SELECT 'link', 'Why Law Firms Outgrow the Marketing Help They Start With', 'A junior hire, a big agency, a stretch of doing nothing. Most firms run that loop before they work out what marketing takes — and why senior, fractional help is the fit.', '', 'https://www.pitchblende.net/insights/why-law-firms-outgrow-their-marketing-help', '', 'https://cdn.prod.website-files.com/6a162fda8d635e31a20caa65/6a3d3296d760b8a7ab61ef3b_6a3d327b54ff1f1446d7048c_pitchblende_cover_B_three-doors%2520(1).png', NULL, 1, 1782345600000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'marketing'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)
WHERE NOT EXISTS (SELECT 1 FROM briefings WHERE url = 'https://www.pitchblende.net/insights/why-law-firms-outgrow-their-marketing-help');

INSERT INTO briefings (kind, title, summary, body, url, cover_key, cover_url, author_id, published, published_at, status, submitted_by, category_id, created_at, updated_at)
SELECT 'link', 'Staffing Is a Two-Sided Sale. Most Firms Run Half of It.', 'Every placement needs a client and a candidate, but most staffing firms market only the client side. Why winning the candidate audience is what makes a recruiting firm grow.', '', 'https://www.pitchblende.net/insights/staffing-marketing-two-sided-sale', '', 'https://cdn.prod.website-files.com/6a162fda8d635e31a20caa65/6a458240b0629733f84313e7_6a4581a010c7b2b17b3c7a9c_pitchblende_cover_staffing_two-sided.png', NULL, 1, 1782864000000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'marketing'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)
WHERE NOT EXISTS (SELECT 1 FROM briefings WHERE url = 'https://www.pitchblende.net/insights/staffing-marketing-two-sided-sale');

INSERT INTO briefings (kind, title, summary, body, url, cover_key, cover_url, author_id, published, published_at, status, submitted_by, category_id, created_at, updated_at)
SELECT 'link', 'How an Independent Practice Out-Markets a DSO', 'DSOs are buying up your market with budgets a single practice can''t match. Why independent dental practices win by owning their neighborhood, not outspending the chain.', '', 'https://www.pitchblende.net/insights/how-independent-dental-practices-out-market-dsos', '', 'https://cdn.prod.website-files.com/6a162fda8d635e31a20caa65/6a4e68007d4ea72b46b8cfef_6a4e67e2242c675568ce06cc_pitchblende_dental_cover_B_concentrated%2520(1).png', NULL, 1, 1783512000000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'marketing'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)
WHERE NOT EXISTS (SELECT 1 FROM briefings WHERE url = 'https://www.pitchblende.net/insights/how-independent-dental-practices-out-market-dsos');

INSERT INTO briefings (kind, title, summary, body, url, cover_key, cover_url, author_id, published, published_at, status, submitted_by, category_id, created_at, updated_at)
SELECT 'link', 'Stop Selling Tax Prep. Start Selling Judgment.', 'Compliance work is commoditizing. Why accounting firms grow by marketing the advice clients can''t get from software, and competing on judgment, not price.', '', 'https://www.pitchblende.net/insights/accounting-firm-marketing-sell-judgment-not-tax-prep', '', 'https://cdn.prod.website-files.com/6a162fda8d635e31a20caa65/6a563fd83765ccc2cf4bccc3_6a563ddf7619608bb43f0897_optionC_split-diptych.png', NULL, 1, 1784044800000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'marketing'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)
WHERE NOT EXISTS (SELECT 1 FROM briefings WHERE url = 'https://www.pitchblende.net/insights/accounting-firm-marketing-sell-judgment-not-tax-prep');

INSERT INTO briefings (kind, title, summary, body, url, cover_key, cover_url, author_id, published, published_at, status, submitted_by, category_id, created_at, updated_at)
SELECT 'link', 'When You''re Booked Solid, What''s Marketing For?', 'The vet shortage left many practices at capacity. When the schedule''s already full, marketing''s job shifts from chasing new clients to attracting the right ones and keeping them for life.', '', 'https://www.pitchblende.net/insights/veterinary-marketing-when-youre-booked-solid', '', 'https://cdn.prod.website-files.com/6a162fda8d635e31a20caa65/6a6a331fe4249da63b0f3793_6a6a32f698fbbc5e3422dc59_veterinary_blog_wide%2520(1).png', NULL, 1, 1785326400000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'marketing'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)
WHERE NOT EXISTS (SELECT 1 FROM briefings WHERE url = 'https://www.pitchblende.net/insights/veterinary-marketing-when-youre-booked-solid');

INSERT INTO briefings (kind, title, summary, body, url, cover_key, cover_url, author_id, published, published_at, status, submitted_by, category_id, created_at, updated_at)
SELECT 'link', 'Your Paid Media Problem Probably Isn''t in the Ad Account', 'Matthew Simpson went on The Marketing Share to talk budget, channels and attribution. Most of the answers ended up somewhere above the ad account.', '', 'https://www.pitchblende.net/insights/paid-media-problem-isnt-the-ad-account', '', 'https://cdn.prod.website-files.com/6a162fda8d635e31a20caa65/6a733c9f3c1b7d217b30eb72_maxresdefault.jpeg', NULL, 1, 1785931200000, 'approved', NULL, (SELECT id FROM briefing_categories WHERE slug = 'marketing'), (strftime('%s','now') * 1000), (strftime('%s','now') * 1000)
WHERE NOT EXISTS (SELECT 1 FROM briefings WHERE url = 'https://www.pitchblende.net/insights/paid-media-problem-isnt-the-ad-account');
